name: Docker Image CI

on:
  push:
    branches: [ "AMQP" ]
  pull_request:
    branches: [ "AMQP" ]

jobs:

  build:

    runs-on: [DESKTOP-3FBH9V8]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
