name: Create docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    environment: deploy-env

    steps:
      - name: Create docker
        run: |
          GIT_VERSION =$(git describe --abbrev=0 --tags)
          echo "Update version package..."
          docker-compose build --no-cache
          docker pull agrubio/rest-api:$GIT_VERSION
